user_management/user_management/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', views.homepage, name='home'),

	# path('users/', include('django.contrib.auth.urls')), # This line is added to include the built-in django authentication URLs
	path('users/', include('users.urls')),

	path('accounts/', include('allauth.urls')), # This line is added to include the allauth URLs
]

user_management/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('login/', views.login_user, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('register/', views.register_user, name='register'),

	path('profile/', views.profile, name='profile'),
]

user_management/users/models.py
from django.db import models

# Create your models here.

user_management/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)
	# email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	# first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	# last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	# def __init__(self, *args, **kwargs):
	# 	super(RegisterUserForm, self).__init__(*args, **kwargs)
	
	# 	self.fields['username'].widget.attrs['class'] = 'form-cntrol'
	# 	self.fields['password1'].widget.attrs['class'] = 'form-cntrol'
	# 	self.fields['password2'].widget.attrs['class'] = 'form-cntrol'

user_management/user_management/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'home.html')

user_management/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm


def login_user(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.error(request, 'Invalid username or password')
			return redirect('users:login')
	else:
		return render(request, 'users/login.html', {})

def logout_user(request):
	# if requestmethod == 'POST':
	logout(request)
	messages.success(request, 'You have been logged out.')
	return redirect('home')

def register_user(request):
	if request.method == 'POST':
		form = RegisterUserForm(request.POST)
		# form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, f'Registration successful. Account created for {username}')
			return redirect('home')
	else:
		form = RegisterUserForm()
		# form = UserCreationForm()
	return render(request, 'users/register.html', {'form': form})

def profile(request):
	return render(request, 'users/profile.html', {})

user_management/templates/home.html
{% extends "layout.html" %}

{% block title %}
	<title>HOME</title>
{% endblock title %}

{% block content %}
	<h1>This is the HOME PAGE !</h1>
{% endblock content %}

user_management/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>
		{% block title %}
			User Managemant
		{% endblock %}
	</title>

</head>

<body>

	<nav>
		<a href="/" title="HOME">Home</a> |
		{% if user.is_authenticated %}
			<a href="{% url 'users:logout' %}" title="LOGOUT">Logout</a> |
			<span style="float: right;">You are logged in as [ {{ user.username }} ]</span>
		{% else %}
			<a href="{% url 'users:login' %}" title="LOGIN">User Login</a> |
			<a href="{% url 'users:register' %}" title="REGISTER">Registration</a>
		{% endif %}
	</nav>

	<main>
		{% block content %}
		{% endblock %}
		<div>
			{% block messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endblock %}
		</div>
	</main>

</body>

</html>

user_management/users/templates/users/login.html
{% extends 'layout.html' %}

{% block content %}

	<h2>Login</h2>
	<form method="POST">

		{% csrf_token %}

		<div>
			<label for="username">Username:</label>
			<input type="text" name="username">
		</div>

		<div>
			<label for="password">Password:</label>
			<input type="password" name="password">
		</div>

		<button type="submit">Login</button>

	</form>

{% endblock %}

user_management/users/templates/users/profile.html
{% extends "layout.html" %}

{% block title %}
	<title>Profile Page</title>
{% endblock title %}

{% block content %}
	<h1>This is your profile page. You are logged in as [{{ request.user.username }}]</h1>

	{% comment %} <a href="{% url 'users:edit' %}">Edit Profile</a> {% endcomment %}
	{% comment %} <a href="{% url 'users:change_password' %}">Change Password</a> {% endcomment %}
	{% comment %} <a href="{% url 'users:delete' %}">Delete Account</a> {% endcomment %}
	<a href="{% url 'users:logout' %}">Logout</a>


{% endblock content %}

user_management/users/templates/users/register.html
{% extends 'layout.html' %}

{% block content %}

{% if form.errors %}
	<p>There was an error with the form. Please try again.</p>
{% endif %}

	<h2>Register</h2>
	<form action="{% url 'users:register' %}" method="POST">

		{% csrf_token %}

		{{ form.as_p }}

		<button type="submit">Submit</button>

	</form>

{% endblock %}